apiVersion: v1
kind: Secret
metadata:
  name: kube-controller-manager
  namespace: kube-system
type: Opaque
data:
  service-account.key: ${serviceaccount_key}
  root-ca.crt: ${root_ca_cert}
  kube-ca.crt: ${kube_ca_cert}
  kube-ca.key: ${kube_ca_key}
