# KubeConfigInCluster instructs clients to use their service account token,
# but unlike an in-cluster client doesn't rely on the `KUBERNETES_SERVICE_PORT`
# and `KUBERNETES_PORT` to determine the API servers address.
#
# This kubeconfig is used by bootstrapping pods that might not have access to
# these env vars, such as kube-proxy, which sets up the API server endpoint
# (chicken and egg), and the checkpointer, which needs to run as a static pod
# even if the API server isn't available.
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeconfig-in-cluster
  namespace: kube-system
data:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - name: ${cluster_name}
      cluster:
        server: ${server}
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    users:
    - name: service-account
      user:
        # Use service account token
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    contexts:
    - context:
        cluster: ${cluster_name}
        user: service-account